//! Parse and atomically rewrite `.env` files.

use crate::config::{FieldSpec, FieldTier, FIELD_CATALOG};
use chrono::Utc;
use std::collections::HashMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub struct SaveResult {
    pub path: PathBuf,
    pub backup: Option<PathBuf>,
}

/// Pulls KEY=value pairs out of a dotenv-style file. Comments and blank lines
/// are ignored. Unknown keys are preserved by the caller, not here.
pub fn parse_env_file(contents: &str) -> HashMap<String, String> {
    let mut values = HashMap::new();

    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let Some((key, value)) = trimmed.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if key.is_empty() {
            continue;
        }
        values.insert(key.to_string(), unquote(value.trim()));
    }

    values
}

/// Writes `values` as a commented `.env`, preserving keys that are not in the
/// catalog. Existing files are backed up only when the new contents differ.
pub fn save_env(
    path: &Path,
    values: &HashMap<String, String>,
    previous: Option<&str>,
) -> io::Result<SaveResult> {
    let unknown = unknown_keys(values, previous);
    let rendered = render_env_file(values, &unknown);

    let backup = match previous {
        Some(old) if old != rendered => Some(write_backup(path, old)?),
        _ => None,
    };

    write_atomic(path, &rendered)?;

    Ok(SaveResult {
        path: path.to_path_buf(),
        backup,
    })
}

pub fn mask_secret(value: &str) -> String {
    if value.is_empty() {
        return "••••".to_string();
    }
    let last: String = value
        .chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect();
    format!("••••{last}")
}

fn unknown_keys(values: &HashMap<String, String>, previous: Option<&str>) -> Vec<(String, String)> {
    let Some(previous) = previous else {
        return Vec::new();
    };

    let mut unknown = Vec::new();
    for (key, value) in parse_env_file(previous) {
        if FieldSpec::get(&key).is_none() && !values.contains_key(&key) {
            unknown.push((key, value));
        }
    }
    unknown.sort_by(|a, b| a.0.cmp(&b.0));
    unknown
}

pub(crate) fn render_env_file(
    values: &HashMap<String, String>,
    unknown: &[(String, String)],
) -> String {
    let mut out = String::new();
    out.push_str("# WatchTower configuration.\n");
    out.push_str("#\n");
    out.push_str("# Generated by `watchtower setup`. Re-run it to change values, or edit this\n");
    out.push_str("# file directly. Treat it as a credential file (mode 600).\n");
    out.push_str("#\n");
    out.push_str(
        "# The daemon refuses to start on an invalid value rather than falling back silently.\n",
    );

    write_tier(&mut out, values, FieldTier::Required, "Required");
    write_recommended(&mut out, values);
    write_tier(&mut out, values, FieldTier::Advanced, "Advanced");

    if !unknown.is_empty() {
        out.push('\n');
        out.push_str("# ── Additional keys (preserved from the previous file) ");
        out.push_str(&"─".repeat(20));
        out.push('\n');
        for (key, value) in unknown {
            out.push_str(&format!("{key}={}\n", escape_env_value(value)));
        }
    }

    out
}

fn write_tier(out: &mut String, values: &HashMap<String, String>, tier: FieldTier, heading: &str) {
    if tier == FieldTier::Recommended {
        return;
    }

    out.push('\n');
    out.push_str(&format!("# ── {heading} "));
    out.push_str(&"─".repeat(70usize.saturating_sub(heading.len())));
    out.push('\n');

    for field in FIELD_CATALOG.iter().filter(|field| field.tier == tier) {
        write_field(out, field, values.get(field.key).map(String::as_str));
    }
}

fn write_recommended(out: &mut String, values: &HashMap<String, String>) {
    out.push('\n');
    out.push_str("# ── Recommended ");
    out.push_str(&"─".repeat(62));
    out.push('\n');

    let gecko_set = values
        .get("COINGECKO_API_KEY")
        .map(|value| !value.is_empty())
        .unwrap_or(false);
    let rpc_set = values.get("SOLANA_RPC_ENDPOINTS").is_some();
    if !gecko_set || !rpc_set {
        out.push_str(
            "# Public defaults are fine for a throwaway test. For anything you rely on,\n",
        );
        out.push_str(
            "# set a CoinGecko API key and a private Solana RPC (re-run `watchtower setup`).\n",
        );
    }

    for field in FIELD_CATALOG
        .iter()
        .filter(|field| field.tier == FieldTier::Recommended)
    {
        write_field(out, field, values.get(field.key).map(String::as_str));
    }
}

fn write_field(out: &mut String, field: &FieldSpec, value: Option<&str>) {
    out.push('\n');
    for line in field.explanation.lines() {
        if line.is_empty() {
            out.push_str("#\n");
        } else {
            out.push_str("# ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if let Some(how) = field.how_to_get {
        out.push_str("#\n# How to get it:\n");
        for line in how.lines() {
            out.push_str("# ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("#\n# ");
    out.push_str(field.constraints);
    out.push('\n');

    match value {
        Some(value) => {
            out.push_str(field.key);
            out.push('=');
            out.push_str(&escape_env_value(value));
            out.push('\n');
        }
        None => {
            out.push_str("# ");
            out.push_str(field.key);
            out.push('=');
            if let Some(default) = field.default {
                out.push_str(default);
            }
            out.push('\n');
        }
    }
}

fn escape_env_value(value: &str) -> String {
    if value
        .chars()
        .any(|ch| ch.is_whitespace() || matches!(ch, '#' | '"' | '\''))
    {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

fn unquote(value: &str) -> String {
    let bytes = value.as_bytes();
    if bytes.len() >= 2
        && ((bytes[0] == b'"' && *bytes.last().unwrap() == b'"')
            || (bytes[0] == b'\'' && *bytes.last().unwrap() == b'\''))
    {
        value[1..value.len() - 1]
            .replace("\\\"", "\"")
            .replace("\\\\", "\\")
    } else {
        value.to_string()
    }
}

fn write_backup(path: &Path, contents: &str) -> io::Result<PathBuf> {
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(".env");
    let stamp = Utc::now().format("%Y%m%dT%H%M%SZ");
    let backup = path.with_file_name(format!("{name}.bak.{stamp}"));
    write_atomic(&backup, contents)?;
    Ok(backup)
}

fn write_atomic(path: &Path, contents: &str) -> io::Result<()> {
    let tmp = {
        let mut tmp = path.as_os_str().to_os_string();
        tmp.push(".tmp");
        PathBuf::from(tmp)
    };

    fs::write(&tmp, contents)?;
    set_private_mode(&tmp)?;
    fs::rename(&tmp, path)?;
    // Rename does not always preserve mode on every filesystem; set it again.
    set_private_mode(path)?;
    Ok(())
}

fn set_private_mode(path: &Path) -> io::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct Scratch(PathBuf);

    impl Scratch {
        fn new() -> Self {
            let dir = std::env::temp_dir().join(format!(
                "watchtower-setup-{}-{}",
                std::process::id(),
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            fs::create_dir_all(&dir).unwrap();
            Self(dir)
        }

        fn path(&self, name: &str) -> PathBuf {
            self.0.join(name)
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn required_values() -> HashMap<String, String> {
        HashMap::from([
            (
                "TELEGRAM_BOT_TOKEN".to_string(),
                "1234567890:AAEhBOweik6ad".to_string(),
            ),
            ("ADMIN_TELEGRAM_IDS".to_string(), "111".to_string()),
        ])
    }

    #[test]
    fn parse_env_file_skips_comments_and_unquotes() {
        let parsed = parse_env_file(
            "\n# comment\nTELEGRAM_BOT_TOKEN=abc\nQUOTED=\"hello world\"\nEMPTY=\nNOEQ\n",
        );
        assert_eq!(parsed.get("TELEGRAM_BOT_TOKEN").unwrap(), "abc");
        assert_eq!(parsed.get("QUOTED").unwrap(), "hello world");
        assert_eq!(parsed.get("EMPTY").unwrap(), "");
        assert!(!parsed.contains_key("NOEQ"));
    }

    #[test]
    fn render_includes_required_values_and_comments_defaults() {
        let rendered = render_env_file(&required_values(), &[]);
        assert!(rendered.contains("TELEGRAM_BOT_TOKEN=1234567890:AAEhBOweik6ad"));
        assert!(rendered.contains("ADMIN_TELEGRAM_IDS=111"));
        assert!(rendered.contains("# DATABASE_URL=sqlite://data/watchtower.db"));
        assert!(rendered.contains("# COINGECKO_API_KEY="));
        assert!(rendered.contains("watchtower setup"));
        assert!(rendered.contains("Anyone who has the token"));
    }

    #[test]
    fn render_preserves_unknown_keys() {
        let rendered = render_env_file(
            &required_values(),
            &[("CUSTOM_FLAG".to_string(), "on".to_string())],
        );
        assert!(rendered.contains("CUSTOM_FLAG=on"));
        assert!(rendered.contains("Additional keys"));
    }

    #[test]
    fn save_env_writes_mode_600_and_backs_up_on_change() {
        let scratch = Scratch::new();
        let path = scratch.path(".env");
        fs::write(
            &path,
            "TELEGRAM_BOT_TOKEN=old\nADMIN_TELEGRAM_IDS=1\nKEEP_ME=yes\n",
        )
        .unwrap();

        let result = save_env(
            &path,
            &required_values(),
            Some(&fs::read_to_string(&path).unwrap()),
        )
        .unwrap();

        let written = fs::read_to_string(&path).unwrap();
        assert!(written.contains("TELEGRAM_BOT_TOKEN=1234567890:AAEhBOweik6ad"));
        assert!(written.contains("KEEP_ME=yes"));
        assert!(result.backup.is_some());
        let backup = fs::read_to_string(result.backup.as_ref().unwrap()).unwrap();
        assert!(backup.contains("TELEGRAM_BOT_TOKEN=old"));
        assert!(backup.contains("KEEP_ME=yes"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "expected 600, got {mode:o}");
        }
    }

    #[test]
    fn save_env_skips_backup_when_contents_are_unchanged() {
        let scratch = Scratch::new();
        let path = scratch.path(".env");
        let rendered = render_env_file(&required_values(), &[]);
        fs::write(&path, &rendered).unwrap();

        let result = save_env(&path, &required_values(), Some(&rendered)).unwrap();
        assert!(result.backup.is_none());
    }

    #[test]
    fn mask_secret_keeps_last_four() {
        assert_eq!(mask_secret("1234567890:AAEhBOweik6ad"), "••••k6ad");
        assert_eq!(mask_secret(""), "••••");
        assert_eq!(mask_secret("ab"), "••••ab");
    }

    #[test]
    fn write_is_atomic_relative_to_the_target() {
        let scratch = Scratch::new();
        let path = scratch.path(".env");
        write_atomic(&path, "ok=1\n").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "ok=1\n");
        // leftover tmp must not replace a later successful write
        fs::write(scratch.path(".env.tmp"), "stale").unwrap();
        write_atomic(&path, "ok=2\n").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "ok=2\n");
        assert!(!path.with_file_name(".env.tmp").exists());
    }

    #[test]
    fn rendered_env_is_accepted_by_settings() {
        let mut values = required_values();
        values.insert(
            "SOLANA_RPC_ENDPOINTS".to_string(),
            "https://rpc.example".to_string(),
        );
        let rendered = render_env_file(&values, &[("KEEP_ME".to_string(), "yes".to_string())]);
        let parsed = parse_env_file(&rendered);
        crate::config::Settings::from_env_map(&parsed).unwrap();
        assert_eq!(parsed.get("KEEP_ME").unwrap(), "yes");
    }
}
